- msys2-installer/make-msys2-installer
The available pacman executable does not know the `-rootrebase` option,
therefore we need to use the `-root` option.
This developer suggests that the `-rootrebase` option was introduced to
ask pacman to rebase the .dll files after installing everything into a
new root directory. However, we only ever plan to develop Git for
Windows on 64-bit setups, therefore rebasing is substantially less
crucial for us and we can totally live without it.
Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>
> Fix building the MSYS2 installer

- pacman/pacman.conf.i686
- pacman/pacman.conf.x86_64
List it first so git-for-windows can override mingw / msys packages.
Signed-off-by: Sebastian Schuberth <sschuberth@gmail.com>
> Introduce the git-for-windows repository to pacman

- pacman/pacman.conf
Unfortunately, Pacman cannot handle the case where packages of the same
name but for different architectures are available.
So we still need to have two different repositories, one for i686 and
one for x86_64.
Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>
> Switch the Git-for-Windows Pacman repository to the Bintray one

- git-extra/PKGBUILD
The package `git-extra` will deploy files such as `vimrc` or the default
global git configuration for the MinGW git environment.
Notes:
- https://github.com/git-for-windows/build-extra/pull/6 has to be merged before this or the build will fail.
- before first installation on existing environment the files like `vimrc`, `vi` or `git.sh` has to be removed manually or `pacman` will see a file conflict.
- this is for https://github.com/git-for-windows/git/issues/31
> git-extra-package

- readline/PKGBUILD
- readline/readline-6.3-paste-utf8.patch
The call to GetClipboardData(CF_TEXT) returns the text in the system
encoding, which was then incorrectly treated as UTF-8 encoded. Instead we
need to use GetClipboardData(CF_UNICODETEXT) to get the text in UTF-16,
followed by a conversion to UTF-8.
Also fixed a problem were CloseClipboard was only called if
GetClipboardData returns non-null. According to the documentation, every
successful call to OpenClipboard should be matched with a call to
CloseClipboard.
> readline: convert clipboard data to UTF-8 encoding

- msys2-runtime/update-patches.sh
Supersedes #25 and #28 
- Handle the case that `^HEAD^{/Start.the.merging.rebase}` doesn't match anything by checking before calling format-patch.
- Fetch $base_tag from the package source repo (by url) to make sure it exists and isn't stale.
- On one computer I have `diff.algorithm = patience` set in my ~/.gitconfig, and as a result `msys2-runtime/update-patches.sh` Updated a single old patch (0053, at present).
The diff looked significant, and it took me a long long time to realizes it was just different context around changes.
Calling `git format-patch` with relevant `-c` config defaults along with some `format-patch` options that reflect defaults should remedy this most of the time.
> Fix msys2 runtime update patches

- msys2-runtime/0058-fixup-Generate-a-.pdb-file-instead-of-a-.dbg-file.patch
- msys2-runtime/PKGBUILD
Fixes git-for-windows/git#356
This reverts commit c8e710e5525f29abaf8cd18d5e8851133faf9035.
Signed-off-by: Dakota Hawkins <dakotahawkins@gmail.com>
Supersedes #26
> Revert "msys2-runtime-devel: bundle .pdb instead of .dbg files"

- gnupg/0001-gnupg-2.2.9-have-drive-letters.patch
- gnupg/PKGBUILD
Fix the absolute path expansion of Windows paths for --homedir and similar.
> gnupg: enable drive letters support (#1869)

- libcbor/PKGBUILD
- libfido2/0001-cmake-msys-fixes.patch
- libfido2/PKGBUILD
- openssh/PKGBUILD
if you are on Windows 10 version 1903 or higher you need to run git-bash as administrator
> FIDO support for openssh

- .ci/ci-build.sh
- .ci/ci-dont-install-list.txt
- .ci/ci-library.sh
- .ci/fetch-validpgpkeys.sh
- .github/workflows/main.yml
- gnupg/0002-gnupg-2.2.28compile-without-ldap.patch
- gnupg/PKGBUILD
To avoid having to put together a setup with the usual pacman related tools, this PR first adds a build definition to be run via GitHub Actions, and then adds a patch required to build [GNU Privacy Guard v2.2.28](https://github.com/gpg/gnupg/releases/tag/gnupg-2.2.28).
> Add CI and prepare for gnupg v2.2.28

- .ci/ci-build.sh
- pkgconf/001-no-cygpath-conv.patch
- pkgconf/PKGBUILD
The MSYS2 project did that already. But we also need this for the i686 side of things, which MSYS2 no longer updates.
> Let's switch from `pkg-config` to `pkgconf`

- .github/workflows/main.yml
- libgcrypt/PKGBUILD
- libgcrypt/fix-broken-mlock-detection.patch
- libgcrypt/libgcrypt-1.6.1-msys2.patch
- libgpg-error/PKGBUILD
- libgpg-error/gpg-error-static-linking.patch
- libgpg-error/libgpg-error-1.16-msys2.patch
Since MSYS2 stopped servicing their i686 flavor, Git for Windows has to take care of building all kinds of things that we formerly got "for free".
To build `gnupg`, we need an updated `libgcrypt`. For that, we need a newer `libgpg-error` (at least we _thought_ that we did). And to build `libgpg-error`, we need to switch from the `pkg-config` to the `pkgconf` package.
This PR allows us to do all that.
> Allow building GNU Privacy Guard's dependencies

- gnupg/0003-scd-fix-for-SCARD_IO_REQUEST-structure.patch
- gnupg/PKGBUILD
Working as you can see from the commit signature ;)
Fixes: git-for-windows/git#2888
> gnupg: fix smartcard support in 64-bit builds

- bash/PKGBUILD
This addresses https://github.com/git-for-windows/MSYS2-packages/pull/52#issuecomment-1050273853.
> bash: fix build in Git for Windows' i686 SDK

- mintty/PKGBUILD
This PR supercedes https://github.com/git-for-windows/MSYS2-packages/pull/61, using a branch in the git-for-windows/MSYS2-packages repository so that it can be branch-deployed from here.
See https://github.com/mintty/mintty/releases/tag/3.6.2 for details.
This closes https://github.com/git-for-windows/git/issues/4114
> mintty: update to 3.6.2

- .github/workflows/build-and-deploy.yml
When "branch-deploying" packages (i.e. building and publishing packages from PR branches in preparation for merging the PRs), it is currently a bit tricky to know whether i686 and x86_64 flavors have shipped or not. For example, when branch-deploying `bash`, the runs [showed up in the checks](https://github.com/git-for-windows/MSYS2-packages/pull/64#event-7891123466) but gave no clue what was built (or whether the same flavor was built twice):
The `run-name` feature [was recently shipped to help with that](https://github.blog/changelog/2022-09-26-github-actions-dynamic-names-for-workflow-runs/). Let's use it to make it much easier to understand what that particular workflow run is all about. Example: https://github.com/dscho/MSYS2-packages/actions/runs/3547255249
> build-and-deploy: use a nicer display name

- .github/workflows/main.yml
This avoids the loud deprecation warning about node.js 12:
Annotations
1 warning
build
Node.js 12 actions are deprecated. For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16: [...]
> ci: use newer GitHub Actions' versions

- less/PKGBUILD
In 8e6d96af (less: align with MSYS2, 2023-01-26), we tried to align with MSYS2, and we even changed the `depends` and `makedepends` entries of the `PKGBUILD` file.
But we forgot to adjust the `./configure` call ;-)
As a result, Git for Windows' i686 version of `less.exe` (which is not provided by MSYS2 anymore) currently does not even support regular expressions...
This incidentally triggers a bug (hence fixed in `less`' main branch) where searching for any matching term would cause a segmentation fault.
So let's just let `less.exe` link to PCRE2 already.
> less(i686): _actually_ link to PCRE2

- msys2-runtime/0063-Avoid-sharing-cygheaps-across-Cygwin-versions.patch
- msys2-runtime/0064-dumper-avoid-linker-problem-when-libbfd-depends-on-l.patch
- msys2-runtime/PKGBUILD
This is a companion to https://github.com/git-for-windows/msys2-runtime/pull/48 and is designed to fix https://github.com/git-for-windows/git/issues/4255
> Avoid sharing cygheap between msys2 runtime versions

- docbook-xsl-ns/PKGBUILD
- docbook-xsl-ns/docbook-xsl-ns.install
Now that Git for Windows is about to switch to the `git-sdk-32` to build the `mingw-w64-i686-git` package, we better have an i686 version of the prerequisite `docbook-xsl-ns` package, too.
> docbook-xsl-ns: prepare for building an i686 version

- libgpg-error/0003-Avoid-passing-a-signed-parameter-to-isspace-and-frie.patch
- libgpg-error/PKGBUILD
In #100, I deployed the i686 version of `libgpg_error` with a `.dll` whose file name incorrectly starts with `cyg` instead of `msys-`. This broke `gpg.exe` that depends on the correct file name.
I [temporarily prevented `git-sdk-32` from upgrading `libgpg-error`](https://github.com/git-for-windows/git-sdk-32/commit/57987349dfed17b7c0e2656908d8bf1f50564e79) just so that `libgpg-error` could be branch-deployed from _this_ PR, using the expected file name.
> Fix the i686 variant of the `libgpg error` package

- .ci/ci-build.sh
- msys2-runtime-3.3/PKGBUILD
With this change, i686 variants of the Git for Windows SDK will automatically be moved to the v3.3.* train, allowing msys2-runtime to upgrade to v3.4.* (which does not build on i686 anymore).
> msys2-runtime-3.3: replace msys2-runtime in i686 setups

- msys2-runtime/PKGBUILD
These fixes are partially in response to https://github.com/git-for-windows/git/issues/4442
> Some fixes to allow building the MSYS2 runtime

- libfido2/PKGBUILD
When the new libcbor version was deployed, we intended to build the libfido2 dependencee just afterwards so that it would pick up the new version, but timing conspired against us and the i686 variant of libfido2 1.40.0-2 [still links to libcbor 0.10.0-1](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/7787616041/job/21235168385#step:10:57).
So let's bump the `pkgrel` once more.
> i686: rebuild libfido2 to link to the new libcbor version

- .github/workflows/main.yml
GitHub released new versions of actions/checkout and actions/upload-artifact based on node20. Use these new versions to get rid of the warning that node16 is deprecated.
> ci: update actions to use node20

- .github/workflows/main.yml
- curl/PKGBUILD
The main motivation for this is to fix the PR build problem encountered in https://github.com/git-for-windows/MSYS2-packages/pull/198. [The symptom](https://github.com/git-for-windows/MSYS2-packages/actions/runs/11821394230/job/32936178466?pr=198#step:5:10):
> assertion "s->init == 0xbee51da" failed: file "dynbuf.c", line 242, function: Curl_dyn_ptr
Turns out that this was reported [and diagnosed as a curl bug](https://github.com/curl/curl/issues/15496#issuecomment-2461264595), and fixed via https://github.com/msys2/MSYS2-packages/pull/5005 (thanks @lazka for figuring this all out for me!).
This here PR ports that fix to the `curl` package of Git for Windows. While at it, this also drops a couple of unnecessary deviations from the MSYS2 project's `curl` package definition.
> Some fixes for curl 8.11.0

- curl/PKGBUILD
- heimdal/PKGBUILD
- openssh/PKGBUILD
- perl-Clone/PKGBUILD
- perl-HTML-Parser/PKGBUILD
- perl-Locale-Gettext/PKGBUILD
- perl-Net-SSLeay/PKGBUILD
- perl-TermReadKey/PKGBUILD
- perl-XML-Parser/PKGBUILD
- perl-YAML-Syck/PKGBUILD
- perl/PKGBUILD
libcrypt-devel was removed in July 2023, and libcrypt was removed in October 2023.
~also drop some crazy i686 workarounds from vim, because i686 has now been synced so they are no longer necessary.~
> Migrate libcrypt -> libxcrypt.

- msys2-runtime/PKGBUILD
Upstream no longer manually strips the cygwin dll and creates a debug file since https://cygwin.com/git/?p=newlib-cygwin.git;a=commit;h=99bb3e937a0fdbc1e3acbdc7cefb31e54a89a6ac
This means the debug info now moved from msys2-runtime-devel to msys2-runtime staying in the DLL.
We don't really want to install/ship debug infos by default, so we could either re-implement the debug info extraction manually again, or let makepkg build a separate "-debug" package, or just strip everything.
Since the later is the least work and the least special compared to other packages, just enable stripping.
(cherry picked from commit d24e4dabb9cb22af519e46b88eb202efba6387b4)
> msys2-runtime: strip it

- msys2-runtime/PKGBUILD
Third parties commonly code-sign the MSYS2 runtime when ingesting MinGit, as a way to attest the integrity (_not_ to testify that they have vetted all the supply chain!).
This is currently broken, failing with:
SignTool Error: SignedCode::Sign returned error: 0x800700C1
  %1 is not a valid Win32 application.
SignTool Error: An error occurred while attempting to sign: msys-2.0.dll
The reason is that the MSYS toolchain's version of `strip.exe` somehow changes the structure of the output files that are incompatible with `signtool.exe`, as had been identified in ffd1140c74 (bash: avoid stripping after code-signing, 2022-05-02).
Therefore, as of 667799c692 (msys2-runtime: strip it, 2022-12-19), the `msys-2.0.dll` file (and all of the Cygwin utilities like `cygwin-console-helper.exe`) can no …
> msys2-runtime: avoid stripping to allow code-signing again
